# Samplesheet for sample demultiplexing and file naming.
samplesheet: "config/210819-e0015-e0020-16S-samplesheet.txt"
indices: "config/indexfordemux.txt"
lenR1primer: "23"
lenR2primer: "24"
lenR1index: "7"
lenR2index: "7"

# Input directories.
fastqdir: "/oak/stanford/groups/relman/raw_data/dorang/20210819-e0015-e0020-16S"
demux: "workflow/rules/demux.sh"

# Output directories.
demuxdir: "workflow/out/demux"
trimdir: "workflow/out/trimmed"
